# Generated by Django 4.2 on 2026-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_choicelistcolumn_choiceextravalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicelist',
            name='label_column_name',
            field=models.CharField(default='label', help_text="Column header used for the label in CSV export (e.g. 'label::English (en)')", max_length=255),
        ),
    ]
