# Generated by Django 4.2 on 2026-03-23 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_choicelist_name_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.CharField(help_text='Project slug (e.g., aQQv2xc99EodN8pB8GZ6Jq)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('owner', 'slug')},
        ),
    ]
