# Generated by Django 4.2 on 2026-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_phase6_access_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicelist',
            name='name_generation',
            field=models.CharField(choices=[('uuid', 'Random UUID'), ('from_label', 'Derived from label')], default='from_label', help_text='How to auto-generate the choice name/value when adding a new choice', max_length=20),
        ),
    ]
