# Generated by Django 4.2 on 2026-03-27 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_collectionproject_one_collection_per_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChoiceListConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_column_name', models.CharField(blank=True, default='', help_text="Overrides the list's label_column_name in exports. Blank = inherit original.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_configs', to='api.choicelist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'choice_list')},
            },
        ),
        migrations.CreateModel(
            name='UserChoiceListColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='api.userchoicelistconfig')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('config', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserChoiceExtraValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, default='')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_values', to='api.choice')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.userchoicelistcolumn')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_values', to='api.userchoicelistconfig')),
            ],
            options={
                'unique_together': {('config', 'choice', 'column')},
            },
        ),
    ]
